name: Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup and run linter
      run: |
        pip install cpplint
        cpplint  --filter=-legal --linelength=100 *.cpp

    - name: FalsePossitive fail
      run: |
        g++ -Wall -Wextra -Werror *.cpp -o FalsePossitive.out
        bash .github/workflows/expectfail.sh ./FalsePossitive.out
